// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmpgYtShaeAkiWJdQzNuaJKyNIplPoeA',
    appId: '1:589790577019:web:8371b5853f78ba6dc4bdde',
    messagingSenderId: '589790577019',
    projectId: 'fir-app-5fbec',
    authDomain: 'fir-app-5fbec.firebaseapp.com',
    storageBucket: 'fir-app-5fbec.firebasestorage.app',
    measurementId: 'G-8T4L70VTCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9MynQzuF5xts18UKeE_-Ljr1tCGKXI98',
    appId: '1:589790577019:android:689e5a39a4d6d3dfc4bdde',
    messagingSenderId: '589790577019',
    projectId: 'fir-app-5fbec',
    storageBucket: 'fir-app-5fbec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmMWW8FFiskMh3ybhbfulDjZmTJRPcuc',
    appId: '1:589790577019:ios:65aaf23fb3b3a551c4bdde',
    messagingSenderId: '589790577019',
    projectId: 'fir-app-5fbec',
    storageBucket: 'fir-app-5fbec.firebasestorage.app',
    iosBundleId: 'com.yogaapp.yogaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbmMWW8FFiskMh3ybhbfulDjZmTJRPcuc',
    appId: '1:589790577019:ios:65aaf23fb3b3a551c4bdde',
    messagingSenderId: '589790577019',
    projectId: 'fir-app-5fbec',
    storageBucket: 'fir-app-5fbec.firebasestorage.app',
    iosBundleId: 'com.yogaapp.yogaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALmpgYtShaeAkiWJdQzNuaJKyNIplPoeA',
    appId: '1:589790577019:web:b01031c48162dc34c4bdde',
    messagingSenderId: '589790577019',
    projectId: 'fir-app-5fbec',
    authDomain: 'fir-app-5fbec.firebaseapp.com',
    storageBucket: 'fir-app-5fbec.firebasestorage.app',
    measurementId: 'G-LEYEJ6XZT2',
  );
}
